### ISSUE TITLE
Does server supports Promises?

### ISSUE THREAD

**Issue by zubairov** [elasticio/amqp-rpc#1]
e.g. following sample:

```js
server.addCommand('print-hello-world', (name) => {
  console.log('Hello, ${name}!');
  
  return Promise.resolve({foo: 'bar'});
});
```

**Comment by anton-kotenko** [comment]
yes it supports
So you can write any combination of promises/async+awaits/and even throw errors
All this cases would be handled properly. 
Actually it's even used with internal asychrounous calls to k8s in boatswain

**Comment by ghaiklor** [comment]
squashed, tnx 👍
