### ISSUE TITLE
Decoupling RPC Client / Server?

### ISSUE THREAD

**Issue by w1nk** [elasticio/amqp-rpc#14]
Hello!

  I'm attempting to run the RPC server and client in separate processes.  I've been completely unable to do so.  Is there any chance I'm missing something and you have an example of this?  Here's what I've done:

1)  I tried to pass in _requestsQueue to both the client and server so that the names wouldn't be randomly generated.  That then failed as my queue didn't exist since assertQueue will only run when _requestsQueue is empty.  I've temporarily worked around that, but now I'm encountering a new error.

2)  I can launch the server successfully due to my patch from the first step, now I can have the client remotely connect and issue a single rpc request successfully.  The second time I call sendCommand without tearing everything down it fails:

Error: Unknown command print-hello-world

I'm not sure how far down this rabbit hole I should go in case I'm missing something.  Do you have any thoughts on how I can separate the client / server?  Ideally, I'd like to have multiple consumers as well.

Thanks!

**Comment by yarikos** [comment]
1. Actually, there are two ways to use queueName – temporary and permanent one. It was not described well in the documentation. I've updated the [README](https://github.com/elasticio/amqp-rpc/blob/master/README.md), please check it out.

2. It's hard to diagnose by provided description. I've double checked, and could not reproduce the issue. Anyway, I've added extended examples for AMQPRPCServer/Client, where a client sends few consequent requests to a server. I hope it will help you to compare with your code and to find what if you are missing something. Please, follow dir [examples](https://github.com/elasticio/amqp-rpc/tree/master/examples) and look there.

**Comment by w1nk** [comment]
Thanks for the quick reply, sorry I didn't get to this sooner.  Your updated docs and examples are precisely what I needed, thanks! :)
